### PR TITLE
@W-15611884: [MSDK Android] Android Native Login Template Cannot Be Created Due To Invalid Package Names

### PR DESCRIPTION
**Pull request by JohnsonEricAtSalesforce**
🎸 _Ready For Review_ 🥁

  This is an easy one.  The package names in Kotlin for this template changed after it was created and this catches the template script up with that.

### CODE REVIEW

**Comment by brandonpage** [comment]
Where are you seeing a problem with this? `androidnativelogintemplate` seems correct to me.

**Review by wmathurin — CHANGES_REQUESTED** [review]
That does not look right.
I see androidnativelogintemplate in the package path / names e.g. https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate

**Comment by brandonpage** [comment]
@JohnsonEricAtSalesforce Did you enter `com.salesforce.androidnativelogin` as the package when you generated the template?  The actual name and package will be whatever you entered when generating it.  If I enter `com.sfdc.test` that will be the applied everywhere.  

However maybe there is an issue with setting the package correctly if it is a substring?  Maybe there are problems replacing `com.salesforce.androidnativelogintemplate` with `com.salesforce.androidnativelogin`?

**Review by brandonpage — CHANGES_REQUESTED** [review]
Okay, I see the problem now but this is the wrong way to solve it.  

There are a bunch of imports in `NativeLogin` that are **hardcoded** references to other files in the app:
```
import com.salesforce.androidnativelogin.MainApplication.Companion.executeLoginAction
import com.salesforce.androidnativelogin.NativeLoginViewModel.IdentityFlowLayoutType
import com.salesforce.androidnativelogin.NativeLoginViewModel.IdentityFlowLayoutType.InitializePasswordLessLoginViaOtp
import com.salesforce.androidnativelogin.NativeLoginViewModel.IdentityFlowLayoutType.LoginViaUsernameAndOtp
import com.salesforce.androidnativelogin.NativeLoginViewModel.IdentityFlowLayoutType.LoginViaUsernamePassword
import com.salesforce.androidnativelogin.R.drawable.radio_button_checked_24px
import com.salesforce.androidnativelogin.R.drawable.radio_button_unchecked_24px
import com.salesforce.androidnativelogin.R.drawable.sf__salesforce_logo
```

If those get changed to `com.salesforce.androidnativelogintemplate` do they get modified by the script to be the user entered package name?

**Comment by wmathurin** [comment]
That line should take care of it: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/AndroidNativeLoginTemplate/template.js#L61

**Comment by brandonpage** [comment]
I believe this is the correct way to fix the issue: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/408

**Comment by brandonpage** [comment]
Fixed by https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/408

**Pull request closed without merging**
